[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[[bin]]
name="blockchain"
path = "src/main.rs"

[dependencies]
time = "0.3.36"
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.120"
sha2 = "*"
